---
version: 1
disable_existing_loggers: False

formatters:
  empty:
    format:
  pretty:
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%d-%m-%Y %H:%M:%S"

handlers:

  empty_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: empty
    filename: automation.log

  pretty_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: pretty
    filename: automation.log

loggers:
  empty_logger:
    level: INFO
    handlers: [empty_file_handler]
    propagate: no

  pretty_logger:
    level: INFO
    handlers: [pretty_file_handler]
    propagate: no

root:
  level: INFO
  handlers: [empty_file_handler, pretty_file_handler]