browser: chrome
headless: false
url: https://opensource-demo.orangehrmlive.com/
env: qa
credentials:
  username: Admin
  password: admin123

# all browsers supported by Selenium Webdriver
supported_browsers:
  - chrome
  - firefox
  - safari
  - ie
  - edge
  - opera